### ISSUE TITLE
Why greyscale doesn't work?

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/programming-fundamentals#1]
[HERE THE CODE](https://github.com/edoardottt/programming-fundamentals/tree/master/Exercises/exercise44)
I follow [this](https://en.wikipedia.org/wiki/Grayscale#Converting_color_to_grayscale)

**Comment by anushas-dev** [comment]
Hi @edoardottt, not sure if this issue is still relevant, could I attempt this?

**Comment by edoardottt** [comment]
Of course, go ahead :)

**Comment by anushas-dev** [comment]
I seem to get 
```
TypeError: 'tuple' object cannot be interpreted as an integer
~\exercise44.py", line 62, in <module>
    immagini.save(img, "imma.png")
~\immagini.py", line 32, in save
    pngimg.save(filename)
```
Is there a chance it is because the RGB channels (set of 9) are greater than grayscale (set of 3)? 
I might be wrong, as I don't have a full understanding yet.
so, I tried something very basic, although doesn't fully serve the purpose as it doesn't maintain original dimension. Is there a chance it is because the RGB channels (set of 9) are greater than grayscale (set of 3)? 
I might be wrong, as I don't have a full understanding yet.

```
import png

reader = png.Reader(filename='tigre.png')
w, h, png_img, _ = reader.asRGB8()

f = open('imma.png', 'wb')
writer_png = png.Writer(2880, 623, greyscale=True)
writer_png.write(f, png_img)
f.close()
```
![imma.png](https://user-images.githubusercontent.com/95580494/198238384-c067340c-3aea-4e34-8821-688a393dd899.png)

**Comment by edoardottt** [comment]
well, definitely better :)

**Comment by gogognome** [comment]
I fixed the issue and create a pull request for you. 

There were a couple of problems present:

In exercise44.py:
- The variables Cr, Cy and Cb were not assigned in the else blocks.
- grey_scale() did not return tuples with ints but tuples of floats.

In immagini.py:
- The img parameter of the save() function has a tuple per pixel. This
  is now 'flattened' to 3 values in the two-dimensional array.

**Comment by edoardottt** [comment]
Thank you so much @gogognome !!!

**Comment by anushas-dev** [comment]
https://twitter.com/driscollis/status/1639948300441845762/photo/1 has a cool 4-liner code to convert to greyscale. Thanks to @driscollis!
